..\..\Debug\DrawSudoku.exe 1.txt 1.png
..\..\Debug\DrawSudoku.exe 2.txt 2.png
..\..\Debug\DrawSudoku.exe 3.txt 3.png
..\..\Debug\DrawSudoku.exe 4.txt 4.png
..\..\Debug\DrawSudoku.exe 5.txt 5.png
..\..\Debug\DrawSudoku.exe 6.txt 6.png
..\..\Debug\DrawSudoku.exe 7.txt 7.png
..\..\Debug\DrawSudoku.exe 8.txt 8.png
..\..\Debug\DrawSudoku.exe 9.txt 9.png
..\..\Debug\DrawSudoku.exe 10.txt 10.png
..\..\Debug\DrawSudoku.exe 11.txt 11.png
..\..\Debug\DrawSudoku.exe 12.txt 12.png
..\..\Debug\DrawSudoku.exe 13.txt 13.png
..\..\Debug\DrawSudoku.exe 14.txt 14.png
..\..\Debug\DrawSudoku.exe 15.txt 15.png